### ISSUE TITLE
RuntimeError: size mismatch, m1: [128 x 544], m2: [576 x 20] at C:\w\1\s\tmp_conda_3.7_112106\conda\conda-bld\pytorch_1572952932150\work\aten\src\TH/generic/THTensorMath.cpp:197

### ISSUE THREAD

**Issue by Scharfi** [conex-kge/ConEx#1]
Hello,

I am interested to generate embeddings for my KG using ConEx.
I have installed ConEx and tested all the preproduce_reported examples which they all run fine, 
however, I tried to run the main.py (as it is using KINSHIP dataset as default) but it through a RuntimeError  for the size of the layers. 
Do you suggest a better idea on  how to set the right projection size?
![Conex](https://user-images.githubusercontent.com/31705416/90936497-8ecd2580-e405-11ea-9e78-34594e816848.PNG)

**Comment by zhanghh2018** [comment]
I try to run the ConvE by using your code,but I find the result is very high,I suspect there is a problem with the code about the final evaluation index。

**Comment by conex-kge** [comment]
The issue is clearly stated in """ m1: [128 x 544], m2: [576 x20]""" one can not multiply such matrixes. Lets look at little bit in
detail what this error implies
```
import numpy as np
m1=np.random.randn(128,544)
m2=np.random.randn(576,20)
m1@m2 
```
would generate
`ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 576 is different from 544)`


> Do you suggest a better idea on how to set the right projection size?

I am not quite sure what this question exactly implies. Projection size can be calculated as shown [here](https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html)
